"""init

Revision ID: 45e715e526fe
Revises: dd33cb03d01f
Create Date: 2023-02-24 07:48:11.825709

"""

# revision identifiers, used by Alembic.
revision = '45e715e526fe'
down_revision = 'dd33cb03d01f'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
