"""init

Revision ID: e581242559e7
Revises: 45e715e526fe
Create Date: 2023-02-24 08:10:27.311219

"""

# revision identifiers, used by Alembic.
revision = 'e581242559e7'
down_revision = '45e715e526fe'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
